import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const defaultTours = [
  {
    slug: "luxury-sri-lanka-discovery",
    nameEn: "Luxury Sri Lanka Discovery",
    nameKo: "럭셔리 스리랑카 디스커버리",
    category: "Luxury",
    duration: "12 Days",
    nights: 11,
    price: "USD 4,850",
    image: "https://images.unsplash.com/photo-1546708973-c6b75c55c707?q=80&w=1200&auto=format&fit=crop",
    badge: "Bespoke Journey",
    shortEn: "The grand tour — cultural triangle, hill country and the southern coast, all in private villas and heritage estates.",
    shortKo: "문화 삼각지대와 고산지대, 남부 해안까지 프라이빗 빌라와 헤리티지 호텔로 잇는 그랜드 투어.",
    overviewEn: "Twelve unhurried days across the island's finest addresses. Climb Sigiriya before the crowds, take the observation carriage through tea country, and end with slow days behind the ramparts of Galle Fort.",
    overviewKo: "12일간 섬 최고의 명소를 여유롭게 여행합니다. 이른 아침 시기리야 등반, 차밭을 지나는 기차 여행, 갈레 요새에서의 느긋한 마무리.",
    highlights: ["Private climb of Sigiriya Lion Rock", "Scenic first-class Tea Train journey", "Exclusive leopard tracking in Yala", "Colonial luxury stay at Ceylon Tea Trails"],
    inclusions: ["Private chauffeur-guide and luxury vehicle", "5-star luxury accommodation with daily breakfast", "All entrance and conservation fees", "24/7 on-trip concierge in English and Korean"],
    exclusions: ["International airfare", "Visa fees (ETA)", "Personal spa and gratuities"],
    hotels: ["Cape Weligama", "Water Garden Sigiriya", "Ceylon Tea Trails", "Amangalla"],
    categories: ["Luxury", "Culture"],
    itinerary: [
      { day: "01", title: "Arrival in Colombo", text: "VIP airport greeting, private chauffeur transfer to beachfront suite." },
      { day: "02", title: "Colombo to Cultural Triangle", text: "Dambulla Cave Temples with private archaeologist guide." },
      { day: "03", title: "Sigiriya Lion Fortress", text: "Dawn ascent of UNESCO rock fortress before crowds arrive." },
      { day: "04", title: "Minneriya Wild Gathering", text: "Private 4x4 open safari tracking wild elephant herds." },
      { day: "05", title: "Sacred City of Kandy", text: "Temple of the Tooth Relic private viewing during evening puja." },
      { day: "06", title: "Highland Tea Train", text: "First-class scenic observation carriage to Nuwara Eliya." },
      { day: "07", title: "Ceylon Tea Estates", text: "Master tea tasting and planter bungalow high tea at 6,200ft." },
      { day: "08", title: "Nine Arches & Yala", text: "Iconic Ella bridge walk and transfer to luxury tented safari camp." },
      { day: "09", title: "Yala Big Game Safari", text: "Two dedicated game drives targeting Sri Lankan leopard & sloth bears." },
      { day: "10", title: "Galle Dutch Fort", text: "Architectural walking tour through 17th-century ramparts and boutique shops." },
      { day: "11", title: "Southern Ocean R&R", text: "Private catamaran cruise, whale watching, or Ayurvedic spa indulgence." },
      { day: "12", title: "Farewell Sri Lanka", text: "Coastal highway transfer to Colombo airport for return flight." },
    ],
  },
  {
    slug: "ultimate-sri-lanka-golf-escape",
    nameEn: "Ultimate Sri Lanka Golf Escape",
    nameKo: "얼티밋 스리랑카 골프 에스케이프",
    category: "Golf",
    duration: "10 Days",
    nights: 9,
    price: "USD 4,200",
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=1200&auto=format&fit=crop",
    badge: "Signature Golf Tour",
    shortEn: "Four championship courses, five-star stays and a chauffeur between every tee — designed with Korean golf groups in mind.",
    shortKo: "4개 챔피언십 코스와 5성급 숙소, 전 구간 전용 차량 — 한국 골프 그룹을 위한 일정.",
    overviewEn: "Seven rounds across colonial, highland and ocean-side courses. Tee times are confirmed before you fly, caddies and clubs arranged, and every transfer is private. Korean-speaking coordination is available throughout.",
    overviewKo: "콜롬보의 클래식 코스, 고산지대, 바닷가 코스에서 총 7라운드. 티타임은 출발 전 확정되며 캐디와 클럽도 준비됩니다. 한국어 응대 가능.",
    highlights: ["Royal Colombo 1879 historical 18 holes", "Donald Steel designed Victoria Golf Resort overlooking lake", "High altitude colonial golf at Nuwara Eliya Golf Club (6,200 ft)", "Ocean-front links at Shangri-La Hambantota"],
    inclusions: ["7 rounds of golf with pre-booked tee times & green fees", "Dedicated caddie service & motorized carts", "Private luxury coach/van with ample golf bag storage", "5-star resort stays with breakfast"],
    exclusions: ["International flights", "Rental clubs (available on request)"],
    hotels: ["Shangri-La Colombo", "Victoria Golf Resort Kandy", "Grand Hotel Nuwara Eliya", "Shangri-La Hambantota"],
    categories: ["Golf", "Luxury"],
    itinerary: [
      { day: "01", title: "Arrival Colombo", text: "Fast-track VIP greeting, welcome dinner at Royal Colombo Club." },
      { day: "02", title: "Royal Colombo Round 1", text: "18 holes on the historic 1879 layout, afternoon colonial city sights." },
      { day: "03", title: "Royal Colombo Round 2", text: "Morning championship round, private evening seafood dinner." },
      { day: "04", title: "Victoria Golf Resort Kandy", text: "Scenic hill country drive, twilight 9 holes alongside Victoria reservoir." },
      { day: "05", title: "Victoria Championship 18", text: "Full 18 holes on Asia's premier hillside course, Temple of the Tooth evening visit." },
      { day: "06", title: "Nuwara Eliya High Altitude Golf", text: "Highland round at 6,200ft amidst cypress pines and gorse bushes." },
      { day: "07", title: "South Coast Transition", text: "Scenic descent to Southern Ocean, Shangri-La check-in & driving range practice." },
      { day: "08", title: "Shangri-La Golf Resort 18", text: "Championship ocean-side 18 holes, sunset cocktails overlooking Indian Ocean." },
      { day: "09", title: "Final Round or Safari", text: "Optional second 18 holes or private Yala leopard safari." },
      { day: "10", title: "Departure", text: "Private expressway chauffeur transfer to Colombo airport." },
    ],
  },
  {
    slug: "wildlife-and-luxury-adventure",
    nameEn: "Wildlife & Safari Expedition",
    nameKo: "야생 사파리 & 럭셔리 익스페디션",
    category: "Wildlife",
    duration: "8 Days",
    nights: 7,
    price: "USD 3,650",
    image: "https://images.unsplash.com/photo-1549366021-9f761d450615?q=80&w=1200&auto=format&fit=crop",
    badge: "Big Five Safari",
    shortEn: "Deep wilderness encounters in Yala and Wilpattu with resident naturalists and luxury safari camps.",
    shortKo: "전문 자연주의자와 함께하는 얄라 및 윌파투 국립공원 럭셔리 텐트 사파리.",
    overviewEn: "Sri Lanka has the world's highest density of leopards and Asian elephants. Experience thrilling game drives, blue whale tracking off Mirissa, and night safaris from the comfort of ultra-luxury tented suites.",
    overviewKo: "세계 최고 밀도의 표범 서식지 얄라와 거대한 아시아 코끼리 무리, 미히사 대왕고래 탐사까지 스리랑카 야생의 경이로움을 만납니다.",
    highlights: ["Leopard tracking in Yala Block 1", "Private ocean safari for Blue Whales", "Luxury glamping with private plunge pool", "Wilpattu sloth bear expeditions"],
    inclusions: ["All private customized safari jeeps & tracker fees", "Luxury tented camp all-inclusive stays", "Private whale watching catamaran"],
    exclusions: ["International flights", "Travel insurance"],
    hotels: ["Wild Coast Tented Lodge", "Chena Huts by Uga", "Resplendent Ceylon Weligama"],
    categories: ["Wildlife", "Luxury"],
    itinerary: [
      { day: "01", title: "Arrival to Southern Coast", text: "Chauffeur transfer directly to private beachfront villa in Galle." },
      { day: "02", title: "Blue Whale Ocean Expedition", text: "Private boat into deep waters tracking blue whales and spinner dolphins." },
      { day: "03", title: "Into the Yala Wilderness", text: "Check-in to Wild Coast Tented Lodge, sunset cocktail by the dunes." },
      { day: "04", title: "Full Day Yala Safari", text: "Dawn to dusk leopard and sloth bear tracking with lead naturalist." },
      { day: "05", title: "Bundala Bird Sanctuary", text: "Wetlands safari viewing thousands of flamingos and crocodiles." },
      { day: "06", title: "Udawalawe Elephant Sanctuary", text: "Intimate encounters with elephant herds and rehabilitation center." },
      { day: "07", title: "Rainforest Exploration", text: "Guided nature walk through Sinharaja UNESCO biosphere reserve." },
      { day: "08", title: "Return to Colombo", text: "Airport transfer with Colombo luxury shopping stop." },
    ],
  },
  {
    slug: "heritage-and-cultural-triangle",
    nameEn: "Sigiriya & Sacred Kingdoms",
    nameKo: "시기리야 & 고대 왕국 헤리티지",
    category: "Culture",
    duration: "7 Days",
    nights: 6,
    price: "USD 2,950",
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    badge: "UNESCO Heritage",
    shortEn: "Immerse yourself in 2,500 years of royal Sinhalese civilization and sacred Buddhist heritage.",
    shortKo: "2,500년 역사의 싱할라 고대 왕국과 불교 성지를 탐방하는 깊이 있는 문화 여정.",
    overviewEn: "Discover ancient Sigiriya, Polonnaruwa ruins, sacred Anuradhapura stupas, and the golden Temple of the Tooth guided by expert university archaeologists.",
    overviewKo: "전문 고고학 가이드와 함께 시기리야, 폴론나루와, 아누라다푸라, 캔디 불치사를 깊이 있게 탐방합니다.",
    highlights: ["Sunrise Sigiriya fortress ascent", "Polonnaruwa royal palace ruins", "Sacred Bodhi Tree blessing in Anuradhapura", "Private classical Kandyan dance recital"],
    inclusions: ["Licensed archaeologist private guide", "All UNESCO monument passes", "Heritage boutique hotel stays"],
    exclusions: ["International flights"],
    hotels: ["Jetwing Vil Uyana", "Heritance Kandalama", "The Kandy House"],
    categories: ["Culture", "Luxury"],
    itinerary: [
      { day: "01", title: "Arrival to Negombo", text: "Beachfront heritage hotel check-in and Ayurvedic recovery massage." },
      { day: "02", title: "Anuradhapura Ancient Capital", text: "Exploration of Ruwanwelisaya stupa and 2,300-year-old Sri Maha Bodhi tree." },
      { day: "03", title: "Sigiriya Lion Rock", text: "Private early morning ascent to king Kasyapa's palace in the sky." },
      { day: "04", title: "Polonnaruwa & Minneriya", text: "Medieval stone carvings of Gal Vihara followed by elephant safari." },
      { day: "05", title: "Dambulla to Kandy", text: "Golden cave temple frescoes and scenic ascent to royal mountain kingdom." },
      { day: "06", title: "Kandy Sacred Relic", text: "Private access to Temple of the Tooth and Peradeniya Royal Botanic Gardens." },
      { day: "07", title: "Colombo Departure", text: "Chauffeur transfer to Colombo airport for departure." },
    ],
  },
  {
    slug: "ceylon-tea-and-highland-mist",
    nameEn: "Ceylon Tea Trails & Highland Mist",
    nameKo: "실론 티 트레일 & 고산지대 휴양",
    category: "Highlands",
    duration: "6 Days",
    nights: 5,
    price: "USD 3,200",
    image: "https://images.unsplash.com/photo-1589309736404-2e142a2acdf0?q=80&w=1200&auto=format&fit=crop",
    badge: "Highland Retreat",
    shortEn: "Restorative high-altitude escape through emerald tea plantations, waterfalls, and colonial planter bungalows.",
    shortKo: "끝없이 펼쳐진 에메랄드빛 차밭과 폭포, 영국 식민지 시대 플랜터 방갈로에서의 우아한 휴식.",
    overviewEn: "Stay in restored 19th-century colonial planter residences managed by Relais & Châteaux, indulge in high tea, and hike through mist-shrouded cloud forests.",
    overviewKo: "르레앤샤토 공인 19세기 영국 플랜터 저택 방갈로에서 집사의 섬세한 케어와 최고급 실론티를 즐깁니다.",
    highlights: ["Relais & Châteaux Tea Trails bungalow stays", "Scenic train through high mountain passes", "Personal butler service & gourmet dining", "Horton Plains & World's End cliff walk"],
    inclusions: ["All-inclusive planter bungalow accommodation", "Private tea tasting with resident tea master", "First-class scenic train tickets"],
    exclusions: ["International flights"],
    hotels: ["Ceylon Tea Trails Castlereagh", "Ceylon Tea Trails Summerville", "Goatfell Nuwara Eliya"],
    categories: ["Highlands", "Luxury"],
    itinerary: [
      { day: "01", title: "Colombo to Castlereagh Lake", text: "Scenic seaplane or private chauffeur drive into highland tea valley." },
      { day: "02", title: "Tea Trails Experience", text: "Walking the tea fields with pluckers, factory with estate manager." },
      { day: "03", title: "Scenic High Mountain Rail", text: "Historic blue train to Nuwara Eliya, Little England walking tour." },
      { day: "04", title: "Horton Plains & World's End", text: "Dawn trek through cloud forest to 4,000ft sheer drop cliff." },
      { day: "05", title: "Ella Gap & Nine Arches", text: "Private hike to Little Adam's Peak and luxury spa treatment." },
      { day: "06", title: "Descent to Colombo", text: "Transfer to Colombo for evening departure." },
    ],
  },
  {
    slug: "south-coast-wellness-and-ocean-villa",
    nameEn: "Emerald Coastline & Marine Safari",
    nameKo: "남부 에메랄드 코스트 & 해양 사파리",
    category: "Wellness",
    duration: "8 Days",
    nights: 7,
    price: "USD 3,900",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1200&auto=format&fit=crop",
    badge: "Oceanfront Luxury",
    shortEn: "Rejuvenating oceanfront private villas, bespoke Ayurvedic wellness rituals, and pristine southern beaches.",
    shortKo: "프라이빗 해변 빌라, 전통 아유르베다 스파, 남부 바다의 황홀한 석양이 어우러진 웰니스 여정.",
    overviewEn: "Unwind along Sri Lanka's golden southern coast with private cliffside villas, daily personalized yoga, doctor-prescribed Ayurvedic treatments, and sunset champagne cruises.",
    overviewKo: "절벽 위 럭셔리 리조트에서 개인 맞춤 요가와 정통 아유르베다 트리트먼트로 몸과 마음을 치유합니다.",
    highlights: ["Doctor-led bespoke Ayurveda wellness therapy", "Private cliff villa overlooking Indian Ocean", "Private yacht cruise along Mirissa coast", "Galle Fort sunset champagne reception"],
    inclusions: ["Full wellness consultation & daily spa treatments", "Private villa butler service", "Private yacht charter"],
    exclusions: ["International flights"],
    hotels: ["Amanwella Tangalle", "Cape Weligama", "Santani Wellness Kandy"],
    categories: ["Wellness", "Luxury"],
    itinerary: [
      { day: "01", title: "Arrival to Tangalle", text: "Expressway chauffeur transfer to Amanwella private beach pool villa." },
      { day: "02", title: "Ayurvedic Consultation", text: "Consultation with Ayurvedic doctor, tailored herbal oil treatment & private yoga." },
      { day: "03", title: "Tangalle Secluded Bays", text: "Day of beach relaxation, turtle nesting private night walk." },
      { day: "04", title: "Transfer to Weligama Cliff", text: "Check-in to Cape Weligama, 60m clifftop infinity pool sunset." },
      { day: "05", title: "Private Yacht & Marine Safari", text: "Half-day private luxury catamaran sail tracking dolphins and marine life." },
      { day: "06", title: "Galle Fort Heritage Evening", text: "Guided walking tour of 17th century UNESCO fort with historian." },
      { day: "07", title: "Sound Healing & Spa", text: "Tibetan singing bowl meditation and restorative full body therapy." },
      { day: "08", title: "Departure", text: "Private vehicle transfer to Colombo International Airport." },
    ],
  },
];

const defaultGolfCourses = [
  {
    slug: "royal-colombo-golf-club",
    name: "Royal Colombo Golf Club",
    location: "Colombo",
    holes: 18,
    par: 71,
    duration: "1 Day",
    rounds: 2,
    nights: 2,
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=1200&auto=format&fit=crop",
    textEn: "Established in 1879, the Royal Colombo Golf Club is the second oldest Royal club outside the UK. An oasis in the heart of Colombo with Kelani Valley train track running across.",
    textKo: "1879년 설립된 영국 외 지역에서 두 번째로 오래된 로열 골프 클럽. 콜롬보 도심 속 오아시스로 기차가 코스를 가로지르는 독특한 전통을 자랑합니다.",
    hotelPairing: "Shangri-La Colombo / Galle Face Hotel",
    features: ["Founded 1879", "Historic Kelani Valley Railway track", "Championship Par 71", "Colonial Clubhouse & Pro Shop"],
  },
  {
    slug: "victoria-golf-resort-kandy",
    name: "Victoria Golf Resort Kandy",
    location: "Kandy (Digana)",
    holes: 18,
    par: 73,
    duration: "2-3 Days",
    rounds: 2,
    nights: 2,
    image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=1200&auto=format&fit=crop",
    textEn: "Ranked among the top 100 most scenic golf courses in the world by Golf Digest, designed by Donald Steel amidst rolling hills and Victoria Lake.",
    textKo: "골프 다이제스트 선정 세계 100대 아름다운 코스. 도널드 스틸이 설계한 빅토리아 호수와 산맥을 조망하는 아시아 최고 수준의 챔피언십 리조트.",
    hotelPairing: "Victoria Golf Chalets / The Kandy House",
    features: ["Donald Steel Design", "Ranked in Top 100 Scenic Courses", "Panoramic Lake & Mountain Views", "Equestrian & Tennis facilities"],
  },
  {
    slug: "nuwara-eliya-golf-club",
    name: "Nuwara Eliya Golf Club",
    location: "Nuwara Eliya (Highlands)",
    holes: 18,
    par: 70,
    duration: "2 Days",
    rounds: 2,
    nights: 2,
    image: "https://images.unsplash.com/photo-1592919505780-303950717480?q=80&w=1200&auto=format&fit=crop",
    textEn: "Set at 6,200 feet above sea level, this 1889 Scottish-style links course is fringed by towering pines, eucalyptus trees, and highland tea estates.",
    textKo: "해발 1,890m 고산지대에 위치한 1889년 스코틀랜드풍 링크스 코스. 시원한 기후와 삼나무 숲, 차밭으로 둘러싸여 쾌적한 라운딩이 가능합니다.",
    hotelPairing: "Grand Hotel Nuwara Eliya / Heritance Tea Factory",
    features: ["High Altitude (6,200 ft)", "Colonial Scottish Links Layout", "Cool European Climate Year-Round", "Historic 1889 Clubhouse"],
  },
  {
    slug: "shangri-la-hambantota-golf-resort",
    name: "Shangri-La Golf Resort & Spa",
    location: "Hambantota (South Coast)",
    holes: 18,
    par: 70,
    duration: "2-3 Days",
    rounds: 2,
    nights: 2,
    image: "https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?q=80&w=1200&auto=format&fit=crop",
    textEn: "Sri Lanka's first 18-hole resort golf course, set on a former sapphire mine along the Indian Ocean with lush coconut palm fairways and dune bunkers.",
    textKo: "인도양 해안을 따라 조성된 스리랑카 최초의 18홀 럭셔리 리조트 코스. 야자수 페어웨이와 바닷바람이 어우러진 환상적인 라운딩.",
    hotelPairing: "Shangri-La Hambantota Resort & Spa",
    features: ["Oceanfront Resort Course", "Rodney Wright Design", "Sapphire Mine Lake Hazards", "Luxury Spa & 5-Star Dining on site"],
  },
  {
    slug: "eagles-catalina-golf-club",
    name: "Eagles' Catalina Golf Club",
    location: "Koggala (Galle Coast)",
    holes: 9,
    par: 36,
    duration: "1 Day",
    rounds: 1,
    nights: 1,
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    textEn: "Picturesque 9-hole layout located along the southern coast near Koggala Lake, named after the historic WWII Catalina flying boats.",
    textKo: "갈레 남부 코갈라 호수 인근의 그림 같은 9홀 코스. 2차 세계대전 카탈리나 수상기 비행장의 역사적 정취를 담고 있습니다.",
    hotelPairing: "Amangalla / Fortress Resort & Spa",
    features: ["Coastal Breeze Layout", "Water Hazard Challenges", "Near Galle Dutch Fort", "Relaxed Scenic Round"],
  },
];

const defaultDestinations = [
  {
    slug: "sigiriya-and-cultural-triangle",
    nameEn: "Sigiriya & Cultural Triangle",
    nameKo: "시기리야 & 문화 삼각지대",
    region: "North Central",
    duration: "3-4 Days",
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    shortEn: "Home to the 5th-century Lion Rock fortress, cave temples, and sacred ancient cities.",
    shortKo: "5세기 사자바위 요새와 석굴 사원, 고대 싱할라 왕국의 유적이 살아 숨 쉬는 곳.",
    descriptionEn: "The epicenter of Sri Lankan antiquity containing five UNESCO World Heritage sites including Sigiriya fortress, Dambulla caves, and the sacred stupas of Anuradhapura.",
    descriptionKo: "스리랑카 고대 문명의 심장부로 시기리야, 담불라, 폴론나루와 등 5개의 유네스코 세계문화유산이 집약되어 있습니다.",
    highlights: ["Sigiriya Lion Rock climb", "Dambulla Cave monastery", "Minneriya elephant gathering", "Polonnaruwa royal palace ruins"],
    mapX: 52,
    mapY: 38,
  },
  {
    slug: "tea-country-and-nuwara-eliya",
    nameEn: "Tea Country & Nuwara Eliya",
    nameKo: "고산지대 차밭 & 누와라엘리야",
    region: "Central Highlands",
    duration: "2-3 Days",
    image: "https://images.unsplash.com/photo-1589309736404-2e142a2acdf0?q=80&w=1200&auto=format&fit=crop",
    shortEn: "Emerald plantations, cool mountain air, and colonial heritage in 'Little England'.",
    shortKo: "에메랄드빛 차밭, 서늘하고 쾌적한 고산 기후와 영국풍 헤리티지의 '리틀 잉글랜드'.",
    descriptionEn: "Perched over 6,000 feet up in the mist-covered mountains, famous for producing the world's finest Ceylon single-origin teas, historic bungalows, and Nuwara Eliya Golf Club.",
    descriptionKo: "해발 1,800m 이상의 운무 가득한 고산지대로 최고급 실론티 생산지이자 1889년 골프 클럽이 위치한 휴양지입니다.",
    highlights: ["Ceylon Tea Trails factory tour", "Scenic Highland Rail journey", "Nuwara Eliya Golf Club 18 holes", "Horton Plains World's End hike"],
    mapX: 53,
    mapY: 58,
  },
  {
    slug: "galle-and-southern-coast",
    nameEn: "Galle & Southern Coast",
    nameKo: "갈레 & 남부 해안",
    region: "Southern Province",
    duration: "3-5 Days",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1200&auto=format&fit=crop",
    shortEn: "17th-century Dutch fortress, boutique villas, and world-class surfing beaches.",
    shortKo: "17세기 네덜란드 요새와 고급 부티크 빌라, 황금빛 해변이 어우러진 남부의 보석.",
    descriptionEn: "A fortified maritime UNESCO enclave filled with jewelry boutiques, artisan cafes, clifftop luxury villas, and private marine safari expeditions.",
    descriptionKo: "네덜란드 식민지 시대의 성벽 요새 도시로 부티크 상점, 카페, 절벽 위 럭셔리 빌라가 위치해 있습니다.",
    highlights: ["Galle Fort architectural walking tour", "Blue whale watching private boat", "Stilt fishermen photography", "Beachfront dining & Ayurveda spa"],
    mapX: 38,
    mapY: 88,
  },
  {
    slug: "yala-and-wildlife-reserves",
    nameEn: "Yala National Park & Safari",
    nameKo: "얄라 국립공원 & 야생 사파리",
    region: "South East",
    duration: "2-3 Days",
    image: "https://images.unsplash.com/photo-1549366021-9f761d450615?q=80&w=1200&auto=format&fit=crop",
    shortEn: "World's highest density of wild leopards, elephants, and luxury tented camps.",
    shortKo: "세계 최고 밀도의 야생 표범과 코끼리, 최고급 텐트 롯지가 있는 야생의 보고.",
    descriptionEn: "Spanning across coastal scrub, lagoons, and jungle, Yala is the world's premier destination for spotting the elusive Panthera pardus kotiya leopard.",
    descriptionKo: "해안과 정글이 만나는 스리랑카 대표 국립공원으로 전용 4x4 사파리로 표범과 아시아 코끼리를 추적합니다.",
    highlights: ["Leopard tracking in Block 1", "Wild Coast Tented Lodge stay", "Sloth bear encounters", "Bundala wetland birding"],
    mapX: 74,
    mapY: 82,
  },
  {
    slug: "kandy-and-sacred-hill-country",
    nameEn: "Kandy & Sacred Hill Country",
    nameKo: "캔디 & 성스러운 힐 컨트리",
    region: "Central Province",
    duration: "2 Days",
    image: "https://images.unsplash.com/photo-1546708973-c6b75c55c707?q=80&w=1200&auto=format&fit=crop",
    shortEn: "The last royal kingdom, housing the sacred Temple of the Tooth Relic.",
    shortKo: "성스러운 부처님의 치아 사리가 모셔진 스리랑카 마지막 싱할라 왕국의 수도.",
    descriptionEn: "Nestled in forested hills around a tranquil lake, Kandy is the spiritual heart of the island and home to the Victoria Golf Resort.",
    descriptionKo: "호수를 둘러싼 고즈넉한 산악 도시로 불교 최고 성지 불치사와 아시아 최고의 빅토리아 골프 리조트가 자리하고 있습니다.",
    highlights: ["Temple of the Sacred Tooth Relic", "Victoria Golf Resort 18 holes", "Peradeniya Royal Botanical Gardens", "Kandyan cultural dance recital"],
    mapX: 50,
    mapY: 52,
  },
  {
    slug: "bentota-and-golden-beaches",
    nameEn: "Bentota & Golden Beaches",
    nameKo: "벤토타 & 골든 비치",
    region: "West Coast",
    duration: "2-4 Days",
    image: "https://images.unsplash.com/photo-1625736300986-6bd123fb9e92?q=80&w=1200&auto=format&fit=crop",
    shortEn: "Pristine palm-lined sands, luxury water villas, and Geoffey Bawa architecture.",
    shortKo: "야자수가 드리운 황금빛 모래사장과 제프리 바와 건축 양식의 비치 리조트.",
    descriptionEn: "The luxury beach destination of choice for serene ocean leisure, river lagoon cruises, and turtle conservation reserves.",
    descriptionKo: "스리랑카 서부 최고의 휴양지로 제프리 바와의 건축 유산과 잔잔한 바다 휴양을 즐길 수 있습니다.",
    highlights: ["Geoffrey Bawa Lunuganga Estate", "Madu River mangrove boat safari", "Kosgoda Sea Turtle Hatchery", "Luxury watersports & Ayurvedic spa"],
    mapX: 30,
    mapY: 78,
  },
  {
    slug: "trincomalee-and-eastern-seas",
    nameEn: "Trincomalee & Eastern Coast",
    nameKo: "트린코말리 & 동부 해안",
    region: "Eastern Province",
    duration: "3-4 Days",
    image: "https://images.unsplash.com/photo-1590050752112-9c8c5da0735a?q=80&w=1200&auto=format&fit=crop",
    shortEn: "Calm sapphire waters, Pigeon Island coral snorkeling, and Koneswaram temple.",
    shortKo: "사파이어빛 잔잔한 바다, 피전 아일랜드 산호 스노클링과 코네스와람 사원.",
    descriptionEn: "Sri Lanka's summer paradise (May–September) boasting crystal-clear seas, natural harbors, and cliffside Hindu shrines.",
    descriptionKo: "5월~9월 최고의 맑은 바다를 자랑하는 동부 해안으로 산호초 스노클링과 대왕고래 관찰의 명소입니다.",
    highlights: ["Pigeon Island Marine Park snorkeling", "Koneswaram Hindu cliff temple", "Nilaveli pristine white sands", "Eastern whale watching"],
    mapX: 72,
    mapY: 26,
  },
  {
    slug: "colombo-arts-and-heritage",
    nameEn: "Colombo Arts & Colonial Capital",
    nameKo: "콜롬보 & 코스모폴리탄 수도",
    region: "Western Province",
    duration: "1-2 Days",
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    shortEn: "Cosmopolitan capital blending historic colonial architecture, Michelin fine dining, and Royal Colombo Golf.",
    shortKo: "식민지 시대의 헤리티지 건축, 미식 다이닝과 1879 로열 골프가 공존하는 활기찬 수도.",
    descriptionEn: "The gateway to Sri Lanka featuring Galle Face Green, colonial landmarks, high-end Ceylon gem boutiques, and Ministry of Crab fine dining.",
    descriptionKo: "스리랑카의 관문이자 로열 골프 클럽, 최고급 호텔과 세계적인 크랩 레스토랑이 있는 활기찬 대도시입니다.",
    highlights: ["Royal Colombo Golf Club 1879", "Galle Face Green sunset walk", "Pettah spice market & colonial fort", "Ministry of Crab dining experience"],
    mapX: 28,
    mapY: 66,
  },
];

const defaultExperiences = [
  {
    slug: "private-wildlife-safari",
    titleEn: "Private Big Game Safari with Lead Naturalist",
    titleKo: "수석 자연주의자와 함께하는 프라이빗 빅게임 사파리",
    category: "Wildlife",
    duration: "Full Day",
    location: "Yala & Wilpattu National Parks",
    image: "https://images.unsplash.com/photo-1549366021-9f761d450615?q=80&w=1200&auto=format&fit=crop",
    descriptionEn: "Customized 4x4 open-top safari vehicles tracking leopards, Asian elephants, and sloth bears with wildlife biologists.",
    descriptionKo: "전문 야생 생물학자와 함께 개조된 전용 4x4 사파리 차량으로 표범, 아시아 코끼리, 느림보곰을 추적합니다.",
    highlights: ["Private modified open safari jeep", "Experienced bilingual naturalist guide", "Bush breakfast and iced refreshments inside park"],
  },
  {
    slug: "relais-chateaux-tea-trails",
    titleEn: "Relais & Châteaux Planter Bungalow Living",
    titleKo: "르레앤샤토 티 트레일 방갈로 라이프",
    category: "Highlands",
    duration: "2-3 Days",
    location: "Ceylon Tea Country",
    image: "https://images.unsplash.com/photo-1589309736404-2e142a2acdf0?q=80&w=1200&auto=format&fit=crop",
    descriptionEn: "Indulge in 19th-century British planter luxury with dedicated butler service, lawn croquet, and private tea master tastings.",
    descriptionKo: "19세기 영국 플랜터 저택 방갈로에서 집사의 섬세한 케어와 티 마스터의 프라이빗 테이스팅을 경험합니다.",
    highlights: ["Personal butler service", "High tea at 6,200 ft", "Factory masterclass with estate manager"],
  },
  {
    slug: "exclusive-championship-golf",
    titleEn: "Championship Golf on Historic Courses",
    titleKo: "스리랑카 5대 챔피언십 골프 투어",
    category: "Golf",
    duration: "1-5 Days",
    location: "Colombo, Kandy, Nuwara Eliya, Hambantota",
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=1200&auto=format&fit=crop",
    descriptionEn: "Seamless VIP tee times, dedicated caddies, luxury transfers, and golf bag handling on Sri Lanka's finest courses.",
    descriptionKo: "사전 확정 티타임, 전담 캐디, 전용 차량으로 콜롬보, 캔디, 누와라엘리야 명문 코스를 여유롭게 즐깁니다.",
    highlights: ["Guaranteed prime morning tee times", "Dedicated caddie & electric cart hire", "Korean & English speaking coordinators"],
  },
  {
    slug: "unesco-archaeologist-tour",
    titleEn: "Sunrise Sigiriya with University Archaeologist",
    titleKo: "대학 고고학자와 함께하는 시기리야 일출 탐방",
    category: "Culture",
    duration: "Half Day",
    location: "Sigiriya Lion Rock",
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    descriptionEn: "Ascend King Kasyapa's ancient sky fortress at first light with scholarly narratives into 5th-century hydraulics and frescoes.",
    descriptionKo: "이른 아침 인파가 몰리기 전, 대학 고고학자의 깊이 있는 해설과 함께 5세기 공중 궁전 시기리야를 오릅니다.",
    highlights: ["Private dawn fortress access", "Scholarly insight into ancient frescoes", "Champagne breakfast at panoramic view point"],
  },
  {
    slug: "bespoke-doctor-ayurveda",
    titleEn: "Doctor-Prescribed Authentic Ayurveda & Yoga",
    titleKo: "의사 처방 맞춤 정통 아유르베다 & 요가",
    category: "Wellness",
    duration: "Full Day / Multi-Day",
    location: "Southern Coast & Kandy Hills",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1200&auto=format&fit=crop",
    descriptionEn: "Holistic pulse diagnosis by certified Ayurvedic physicians, herbal medicated oil treatments, and private clifftop yoga.",
    descriptionKo: "공인 아유르베다 의사의 진맥을 통한 체질별 맞춤 오일 트리트먼트와 인도양을 바라보는 프라이빗 요가 세션.",
    highlights: ["Personal Ayurvedic physician consultation", "Shirodhara & herbal body therapies", "Organic wellness diet"],
  },
];

const defaultPosts = [
  {
    slug: "golfing-in-sri-lanka-complete-guide",
    titleEn: "Golfing in Sri Lanka: The Ultimate Guide for Luxury Travelers",
    titleKo: "스리랑카 럭셔리 골프 여행 완벽 가이드",
    category: "Golf",
    author: "Iroshan Jayawickrame",
    readTime: "6 min read",
    publishedAt: "2026-02-15",
    image: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=1200&auto=format&fit=crop",
    excerptEn: "From colonial Scottish links in the highlands to Donald Steel's scenic masterpiece in Kandy, discover the island's best fairways.",
    excerptKo: "고산지대 스코틀랜드풍 링크스부터 캔디의 빅토리아 호수 코스까지 스리랑카 최고 골프장을 소개합니다.",
    contentEn: "Sri Lanka is Asia's most surprising premier golf destination. With courses established over 140 years ago during the British colonial era...",
    contentKo: "스리랑카는 140년 이상의 유서 깊은 골프 역사를 간직한 아시아의 숨겨진 명문 골프 여행지입니다...",
  },
  {
    slug: "best-time-to-visit-sri-lanka",
    titleEn: "When to Visit Sri Lanka: A Season-by-Season Luxury Travel Guide",
    titleKo: "스리랑카를 여행하기 가장 좋은 시기: 시즌별 가이드",
    category: "Travel Tips",
    author: "Iroshan Jayawickrame",
    readTime: "5 min read",
    publishedAt: "2026-01-28",
    image: "https://images.unsplash.com/photo-1546708973-c6b75c55c707?q=80&w=1200&auto=format&fit=crop",
    excerptEn: "Understanding Sri Lanka's dual monsoon pattern ensures sunshine and calm seas throughout the entire year.",
    excerptKo: "스리랑카의 독특한 이중 몬순 기후를 이해하면 1년 365일 언제든 맑고 화창한 여행이 가능합니다.",
    contentEn: "Unlike destinations with a single rainy season, Sri Lanka benefits from two distinct weather patterns that ensure one coast is always bathed in sunshine...",
    contentKo: "스리랑카는 서남부와 동북부의 계절풍이 교차하여 1년 내내 언제나 최적의 여행지를 선택할 수 있습니다...",
  },
  {
    slug: "curating-bespoke-itinerary",
    titleEn: "Inside the Atelier: How We Craft Tailor-Made Private Journeys",
    titleKo: "아틀리에 비하인드: 1:1 맞춤 프라이빗 여정의 설계 과정",
    category: "Culture",
    author: "Iroshan Jayawickrame",
    readTime: "4 min read",
    publishedAt: "2026-01-10",
    image: "https://images.unsplash.com/photo-1588820358172-e16e457e937d?q=80&w=1200&auto=format&fit=crop",
    excerptEn: "Why personal inspection, accredited guide credentials (SLTDA C-1734), and local relationships make all the difference.",
    excerptKo: "공인 라이선스(SLTDA C-1734)와 10년 이상의 현지 노하우가 특별한 여행을 만드는 이유.",
    contentEn: "At Lanka Luxe Journeys, every itinerary begins with a blank sheet of paper and a conversation...",
    contentKo: "Lanka Luxe Journeys에서는 틀에 박힌 패키지가 아닌, 고객과의 대화로부터 모든 여정을 설계합니다...",
  },
  {
    slug: "ceylon-tea-trails-experience",
    titleEn: "The Romance of Ceylon Tea: High Altitude Living in Colonial Estates",
    titleKo: "실론티의 로맨스: 고산지대 플랜터 저택에서의 특별한 하루",
    category: "Highlands",
    author: "Iroshan Jayawickrame",
    readTime: "5 min read",
    publishedAt: "2025-12-20",
    image: "https://images.unsplash.com/photo-1589309736404-2e142a2acdf0?q=80&w=1200&auto=format&fit=crop",
    excerptEn: "Wake up to misty tea valleys, private butler morning tea, and the legacy of James Taylor's Ceylon tea heritage.",
    excerptKo: "안개 자욱한 차밭에서 맞이하는 아침 티와 제임스 테일러의 실론티 역사 이야기.",
    contentEn: "High in the central mountains of Sri Lanka, where the elevation touches 6,000 feet, the climate turns crisp and cool...",
    contentKo: "해발 1,800m 고산지대의 상쾌한 공기와 유서 깊은 티 플랜테이션 방갈로의 우아한 라이프스타일을 소개합니다...",
  },
];

const sampleInquiries = [
  {
    id: "LLJ-2026-1001",
    name: "Park Min-Woo",
    email: "minwoo.park@seoul-travel.kr",
    phone: "+82 10-5542-8891",
    country: "South Korea",
    tourSlug: "ultimate-sri-lanka-golf-escape",
    travelers: "4 Adults (Golf Group)",
    travelDate: "2026-10-15",
    duration: "10 Days",
    budget: "$4,000 - $6,000 per person",
    message: "We are 4 golfers from Seoul looking for 7 rounds including Victoria Golf and Shangri-La. Need Korean speaking coordination and private van with ample luggage capacity.",
    status: "New",
    notes: "Followed up via KakaoTalk. Sent customized 10-day golf itinerary with confirmed tee times.",
  },
  {
    id: "LLJ-2026-1002",
    name: "Dr. Jonathan Reynolds",
    email: "jreynolds@oxford.ac.uk",
    phone: "+44 7911 123456",
    country: "United Kingdom",
    tourSlug: "luxury-sri-lanka-discovery",
    travelers: "2 Adults (Couple)",
    travelDate: "2026-11-04",
    duration: "12 Days",
    budget: "$5,000+ per person",
    message: "Interested in archaeology and Tea Trails bungalow stay. Require a qualified archaeologist guide for Sigiriya and Anuradhapura.",
    status: "In Progress",
    notes: "Iroshan will guide personally due to university archaeology background.",
  },
  {
    id: "LLJ-2026-1003",
    name: "Elena Rostova",
    email: "elena.rostova@geneva-wealth.ch",
    phone: "+41 22 819 4400",
    country: "Switzerland",
    tourSlug: "south-coast-wellness-and-ocean-villa",
    travelers: "2 Adults",
    travelDate: "2026-12-22",
    duration: "8 Days",
    budget: "$6,000+ per person",
    message: "Seeking complete Ayurvedic rejuvenation and private beach villa during festive holidays.",
    status: "Contacted",
    notes: "Reserved Cape Weligama ocean pool residence.",
  },
];

const siteSettings = {
  brandName: "Lanka Luxe Journeys",
  founderName: "Iroshan Jayawickrame",
  founderTitle: "Founder & Licensed Tourist Guide",
  licenseNumber: "C-1734",
  experienceYears: "10+",
  founderBio: {
    en: "Lanka Luxe Journeys is a Sri Lanka based luxury travel company founded by Iroshan Jayawickrame, a professional tourist guide with more than 10 years of experience in the tourism industry. We specialize in private, tailor-made journeys for travelers who value comfort, authentic experiences and personal service.",
    ko: "Lanka Luxe Journeys는 10년 이상의 관광 업계 경력을 가진 공인 전문 가이드 이로샨 자야위크라마(Iroshan Jayawickrame)가 설립한 스리랑카 럭셔리 여행사입니다. 편안함, 진정한 경험, 세심한 1:1 맞춤 서비스를 바탕으로 문화 탐방부터 야생 사파리, 차밭, 해변, 골프 및 웰니스까지 고객만을 위한 잊지 못할 여정을 설계합니다.",
  },
  founderQualifications: [
    "SLTDA Registered Professional Tourist Guide (Licence: C-1734)",
    "Diploma in Archaeology – University of Kelaniya, Sri Lanka",
    "Korean & English Bilingual Travel Coordinator",
    "Specialist in Championship Golf Holidays & VIP Chauffeur Operations",
  ],
  heroHeadline1: {
    en: "Curated Luxury Journeys",
    ko: "품격 있는 맞춤 럭셔리 여정",
  },
  heroHeadline2: {
    en: "Across Ceylon's Finest Horizons",
    ko: "스리랑카의 숨겨진 보석을 만나다",
  },
  heroSubtitle: {
    en: "Bespoke itineraries, championship golf escapes, and private wildlife safaris orchestrated by SLTDA licensed specialists.",
    ko: "10년 경력의 공인 전문 가이드(SLTDA C-1734)가 설계하는 프라이빗 럭셔리 투어, 챔피언십 골프 휴양 및 사파리 여행.",
  },
};

const contact = {
  phone: "+94 77 123 4567",
  whatsapp: "94771234567",
  kakao: "@lankaluxe",
  email: "journeys@lankaluxe.com",
  address: "No. 45, Alfred House Gardens, Colombo 03, Sri Lanka",
};

const whyUs = [
  {
    no: "01",
    title: { en: "Personalized & Tailor-Made Journeys", ko: "맞춤형 프라이빗 여정" },
    text: {
      en: "Every journey is carefully planned from a blank page to match your interests, pace and travel style.",
      ko: "정해진 일정 없이 고객의 취향과 속도에 맞추어 처음부터 새롭게 맞춤 설계합니다.",
    },
  },
  {
    no: "02",
    title: { en: "10+ Years Experience", ko: "10년 이상의 전문성" },
    text: {
      en: "10+ years of experience creating memorable journeys in Sri Lanka.",
      ko: "10년 이상의 전문 경험으로 스리랑카에서 잊지 못할 특별한 여정을 만듭니다.",
    },
  },
  {
    no: "03",
    title: { en: "Golf Tourism Specialists", ko: "골프 여행 전문" },
    text: {
      en: "Specializing in golf holidays for Korean and international guests, including tee time reservations, comfortable stays and luxury transport.",
      ko: "한국 및 글로벌 고객을 위한 5대 챔피언십 코스 티타임 예약, 편안한 숙소, 전용 밴 차량까지 완벽하게 제공합니다.",
    },
  },
  {
    no: "04",
    title: { en: "Handpicked Experiences & Hotels", ko: "엄선된 호텔과 특별한 경험" },
    text: {
      en: "I personally inspect and carefully select the experiences, hotels and services I recommend.",
      ko: "제가 직접 투숙하고 엄선한 숙소와 서비스만을 신뢰를 담아 추천합니다.",
    },
  },
  {
    no: "05",
    title: { en: "Comfort, Safety & Trust", ko: "편안함, 안전 및 신뢰" },
    text: {
      en: "Registered and licensed tourism service provider (SLTDA Licence: C-1734) with modern luxury chauffeur fleets and 24/7 dedicated support.",
      ko: "SLTDA 공인 가이드 라이선스(C-1734) 보유 및 최고급 전용 차량 의전으로 안전하고 편안한 여행을 약속합니다.",
    },
  },
  {
    no: "06",
    title: { en: "Personal Service & Local Support", ko: "현지 맞춤 케어 & 소통" },
    text: {
      en: "Personal service and local support in Sri Lanka during your journey. I personally communicate in English and Korean to ensure a smooth and comfortable experience.",
      ko: "여행 중 스리랑카 현지에서 세심한 지원을 제공하며, 영어와 한국어로 원활하고 편안하게 소통합니다.",
    },
  },
];

const testimonials = [
  {
    id: "1",
    author: "Kim Sung-Hoon",
    role: "CEO & Golf Enthusiast, Seoul",
    country: "South Korea",
    text: {
      en: "Our golf tour in Victoria Kandy and Shangri-La Hambantota was impeccably arranged. Iroshan made sure every tee time, caddie, and transfer was seamless.",
      ko: "캔디 빅토리아와 함반토타 샹그릴라에서 진행한 골프 여행은 완벽했습니다. 이로샨 대표님이 모든 티타임과 캐디, 전용 차량을 세심하게 챙겨주셨습니다.",
    },
    rating: 5,
  },
  {
    id: "2",
    author: "David & Sarah Miller",
    role: "London, UK",
    country: "United Kingdom",
    text: {
      en: "The depth of historical knowledge Iroshan brought to Sigiriya and the cultural triangle transformed our entire understanding of Sri Lanka.",
      ko: "시기리야와 문화 삼각지대에서 이로샨 가이드님이 들려준 깊이 있는 역사 해설은 우리 부부에게 잊을 수 없는 감동을 주었습니다.",
    },
    rating: 5,
  },
  {
    id: "3",
    author: "Lee Ji-Won",
    role: "Travel Journalist, Busan",
    country: "South Korea",
    text: {
      en: "The Ceylon Tea Trails bungalow experience and scenic train carriage were like stepping into a romantic movie. Highest recommendation!",
      ko: "실론 티 트레일 방갈로와 고산지대 기차 여행은 한 편의 영화 같았습니다. 최고의 럭셔리 여행사로 추천합니다!",
    },
    rating: 5,
  },
];

async function main() {
  console.log("🌱 Starting Lanka Luxe Journeys database seed...");

  // 1. Seed Admin User
  const defaultAdminUser = process.env.ADMIN_DEFAULT_USER || "admin";
  const defaultAdminPassword = process.env.ADMIN_DEFAULT_PASSWORD || "admin123";
  const passwordHash = await bcrypt.hash(defaultAdminPassword, 12);

  await prisma.user.upsert({
    where: { username: defaultAdminUser },
    update: { passwordHash },
    create: {
      username: defaultAdminUser,
      passwordHash,
      name: "Iroshan Jayawickrame",
      role: "admin",
    },
  });

  // Also ensure founder username works
  await prisma.user.upsert({
    where: { username: "iroshan" },
    update: { passwordHash },
    create: {
      username: "iroshan",
      passwordHash,
      name: "Iroshan Jayawickrame",
      role: "admin",
    },
  });
  console.log(`✅ Admin users ('${defaultAdminUser}', 'iroshan') initialized.`);

  // 2. Seed Tours
  for (const tour of defaultTours) {
    await prisma.tour.upsert({
      where: { slug: tour.slug },
      update: {
        nameEn: tour.nameEn,
        nameKo: tour.nameKo || null,
        category: tour.category,
        duration: tour.duration,
        nights: tour.nights,
        price: tour.price,
        image: tour.image,
        badge: tour.badge || null,
        shortEn: tour.shortEn || null,
        shortKo: tour.shortKo || null,
        overviewEn: tour.overviewEn || null,
        overviewKo: tour.overviewKo || null,
        highlights: JSON.stringify(tour.highlights || []),
        inclusions: JSON.stringify(tour.inclusions || []),
        exclusions: JSON.stringify(tour.exclusions || []),
        hotels: JSON.stringify(tour.hotels || []),
        categories: JSON.stringify(tour.categories || [tour.category]),
        itinerary: JSON.stringify(tour.itinerary || []),
      },
      create: {
        slug: tour.slug,
        nameEn: tour.nameEn,
        nameKo: tour.nameKo || null,
        category: tour.category,
        duration: tour.duration,
        nights: tour.nights,
        price: tour.price,
        image: tour.image,
        badge: tour.badge || null,
        shortEn: tour.shortEn || null,
        shortKo: tour.shortKo || null,
        overviewEn: tour.overviewEn || null,
        overviewKo: tour.overviewKo || null,
        highlights: JSON.stringify(tour.highlights || []),
        inclusions: JSON.stringify(tour.inclusions || []),
        exclusions: JSON.stringify(tour.exclusions || []),
        hotels: JSON.stringify(tour.hotels || []),
        categories: JSON.stringify(tour.categories || [tour.category]),
        itinerary: JSON.stringify(tour.itinerary || []),
      },
    });
  }
  console.log(`✅ ${defaultTours.length} curated tours seeded.`);

  // 3. Seed Golf Courses
  for (const course of defaultGolfCourses) {
    await prisma.golfCourse.upsert({
      where: { slug: course.slug },
      update: {
        name: course.name,
        location: course.location,
        holes: course.holes,
        par: course.par,
        duration: course.duration,
        rounds: course.rounds,
        nights: course.nights,
        image: course.image,
        textEn: course.textEn,
        textKo: course.textKo || null,
        hotelPairing: course.hotelPairing || null,
        features: JSON.stringify(course.features || []),
      },
      create: {
        slug: course.slug,
        name: course.name,
        location: course.location,
        holes: course.holes,
        par: course.par,
        duration: course.duration,
        rounds: course.rounds,
        nights: course.nights,
        image: course.image,
        textEn: course.textEn,
        textKo: course.textKo || null,
        hotelPairing: course.hotelPairing || null,
        features: JSON.stringify(course.features || []),
      },
    });
  }
  console.log(`✅ ${defaultGolfCourses.length} championship golf courses seeded.`);

  // 4. Seed Destinations
  for (const dest of defaultDestinations) {
    await prisma.destination.upsert({
      where: { slug: dest.slug },
      update: {
        nameEn: dest.nameEn,
        nameKo: dest.nameKo || null,
        region: dest.region,
        duration: dest.duration,
        image: dest.image,
        shortEn: dest.shortEn,
        shortKo: dest.shortKo || null,
        descriptionEn: dest.descriptionEn || null,
        descriptionKo: dest.descriptionKo || null,
        highlights: JSON.stringify(dest.highlights || []),
        mapX: dest.mapX,
        mapY: dest.mapY,
      },
      create: {
        slug: dest.slug,
        nameEn: dest.nameEn,
        nameKo: dest.nameKo || null,
        region: dest.region,
        duration: dest.duration,
        image: dest.image,
        shortEn: dest.shortEn,
        shortKo: dest.shortKo || null,
        descriptionEn: dest.descriptionEn || null,
        descriptionKo: dest.descriptionKo || null,
        highlights: JSON.stringify(dest.highlights || []),
        mapX: dest.mapX,
        mapY: dest.mapY,
      },
    });
  }
  console.log(`✅ ${defaultDestinations.length} destinations seeded.`);

  // 5. Seed Experiences
  for (const exp of defaultExperiences) {
    await prisma.experience.upsert({
      where: { slug: exp.slug },
      update: {
        titleEn: exp.titleEn,
        titleKo: exp.titleKo || null,
        category: exp.category,
        duration: exp.duration,
        location: exp.location,
        image: exp.image,
        descriptionEn: exp.descriptionEn,
        descriptionKo: exp.descriptionKo || null,
        highlights: JSON.stringify(exp.highlights || []),
      },
      create: {
        slug: exp.slug,
        titleEn: exp.titleEn,
        titleKo: exp.titleKo || null,
        category: exp.category,
        duration: exp.duration,
        location: exp.location,
        image: exp.image,
        descriptionEn: exp.descriptionEn,
        descriptionKo: exp.descriptionKo || null,
        highlights: JSON.stringify(exp.highlights || []),
      },
    });
  }
  console.log(`✅ ${defaultExperiences.length} signature experiences seeded.`);

  // 6. Seed Blog Posts
  for (const post of defaultPosts) {
    await prisma.blogPost.upsert({
      where: { slug: post.slug },
      update: {
        titleEn: post.titleEn,
        titleKo: post.titleKo || null,
        category: post.category,
        author: post.author,
        readTime: post.readTime,
        publishedAt: post.publishedAt,
        image: post.image,
        excerptEn: post.excerptEn,
        excerptKo: post.excerptKo || null,
        contentEn: post.contentEn || null,
        contentKo: post.contentKo || null,
      },
      create: {
        slug: post.slug,
        titleEn: post.titleEn,
        titleKo: post.titleKo || null,
        category: post.category,
        author: post.author,
        readTime: post.readTime,
        publishedAt: post.publishedAt,
        image: post.image,
        excerptEn: post.excerptEn,
        excerptKo: post.excerptKo || null,
        contentEn: post.contentEn || null,
        contentKo: post.contentKo || null,
      },
    });
  }
  console.log(`✅ ${defaultPosts.length} journal articles seeded.`);

  // 7. Seed Inquiries
  for (const inq of sampleInquiries) {
    await prisma.inquiry.upsert({
      where: { reference: inq.id },
      update: {
        name: inq.name,
        email: inq.email,
        phone: inq.phone,
        country: inq.country || null,
        tourSlug: inq.tourSlug || null,
        travelers: inq.travelers || null,
        travelDate: inq.travelDate || null,
        duration: inq.duration || null,
        budget: inq.budget || null,
        message: inq.message || null,
        status: inq.status,
        notes: inq.notes || null,
      },
      create: {
        reference: inq.id,
        name: inq.name,
        email: inq.email,
        phone: inq.phone,
        country: inq.country || null,
        tourSlug: inq.tourSlug || null,
        travelers: inq.travelers || null,
        travelDate: inq.travelDate || null,
        duration: inq.duration || null,
        budget: inq.budget || null,
        message: inq.message || null,
        status: inq.status,
        notes: inq.notes || null,
      },
    });
  }
  console.log(`✅ ${sampleInquiries.length} sample inquiries seeded.`);

  // 8. Seed Site Settings
  await prisma.siteSetting.upsert({
    where: { key: "global_site_settings" },
    update: { value: JSON.stringify(siteSettings) },
    create: { key: "global_site_settings", value: JSON.stringify(siteSettings) },
  });

  await prisma.siteSetting.upsert({
    where: { key: "global_contact" },
    update: { value: JSON.stringify(contact) },
    create: { key: "global_contact", value: JSON.stringify(contact) },
  });

  await prisma.siteSetting.upsert({
    where: { key: "global_why_us" },
    update: { value: JSON.stringify(whyUs) },
    create: { key: "global_why_us", value: JSON.stringify(whyUs) },
  });

  await prisma.siteSetting.upsert({
    where: { key: "global_testimonials" },
    update: { value: JSON.stringify(testimonials) },
    create: { key: "global_testimonials", value: JSON.stringify(testimonials) },
  });

  console.log("✅ Global site settings, contact, and founder credentials seeded.");
  console.log("🎉 Database seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
